# Generated by Django 6.1.1 on 2026-09-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_meeting_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='participant_1_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='participant_2_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
