# Generated by Django 6.1.1 on 2026-09-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_participant_1_left_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('PHOTO_THEFT', '사진 도용/부적절한 사진 사용'), ('EDUCATION_FRAUD', '학력 위조'), ('JOB_FRAUD', '직업 위조'), ('CONDITION_FRAUD', '나이 및 조건 위조'), ('SEXUAL_SOLICITATION', '성적인 만남 제안')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', '검토중'), ('RESOLVED_BLACKLISTED', '탈퇴완료'), ('DISMISSED', '반려')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='chat.chatroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
