# Generated by Django 6.1.1 on 2026-09-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='detail',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_evidence/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chat.report')),
            ],
        ),
    ]
