# Generated by Django 6.1.1 on 2026-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('INCOMPLETE', '프로필 미입력'), ('PENDING', '심사중'), ('APPROVED', '승인'), ('REJECTED', '거부')], default='INCOMPLETE', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='body_photo',
            field=models.ImageField(blank=True, null=True, upload_to='approval/body/'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='approval/face/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]