# Generated by Django 6.1.1 on 2026-09-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_approved_user_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
