# Generated by Django 6.1.1 on 2026-09-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_blacklisted_user_rejection_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('GYEONGGI_SEOUL_EAST', '경기/서울 동부'), ('GYEONGGI_SEOUL_WEST', '경기/서울 서부'), ('GANGWON', '강원'), ('CHUNGBUK', '충북'), ('CHUNGNAM', '충남'), ('DAEJEON', '대전'), ('GYEONGBUK', '경북'), ('GYEONGNAM', '경남'), ('DAEGU', '대구'), ('BUSAN', '부산'), ('ULSAN', '울산'), ('JEONBUK', '전북'), ('JEONNAM', '전남'), ('GWANGJU', '광주'), ('JEJU', '제주')], max_length=30),
        ),
    ]
