# Generated by Django 6.1.1 on 2026-09-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_hobby_dislike_alter_user_hobby_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='kakao_profile/'),
        ),
    ]
