# Generated by Django 6.1.1 on 2026-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='showcase_photo',
            field=models.ImageField(blank=True, upload_to='showcase/'),
        ),
    ]
