"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일에 적어둔 값을 환경변수로 불러온다. (카카오 앱 키, 시크릿 등 민감정보는 여기서만 읽는다)
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-$e1bcvmz#@y8s=vhp8blq(=#f@4j=v&shqw3(l#et2hz#&2_-q",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# 로컬 개발용 기본값 + 배포 시 .env(또는 호스팅 플랫폼의 환경변수)에 실제 도메인을 콤마로 나열.
# 예: DJANGO_ALLOWED_HOSTS=2535cjzok.up.railway.app
ALLOWED_HOSTS = ["localhost", "127.0.0.1"] + [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]
# Django 4+는 HTTPS로 들어오는 POST(로그인 등)를 CSRF 검증할 때 이 목록에 있는 origin만 신뢰한다.
# 배포한 도메인을 https://까지 포함해서 넣어야 한다. 예: https://2535cjzok.up.railway.app
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]

# 배포 환경(DEBUG=False)에서는 쿠키가 HTTPS로만 오가게 강제한다 (로컬 http 개발 환경은 예외).
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# nginx가 "원래 요청은 https였다"고 알려주는 헤더(X-Forwarded-Proto)를 Django가 믿게 한다.
# 이게 없으면 Django는 nginx와 gunicorn 사이의 http 연결만 보고 http라고 착각해서
# 카카오 콜백 주소를 http://로 만든다 (KOE006의 원인).
# 배포 환경(DEBUG=False)에서만 켠다: 로컬 runserver는 앞에 프록시가 없어서 헤더를 믿으면 안 되기 때문.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # allauth가 요구하는 사이트 프레임워크

    'accounts',  # 우리 회원 앱
    'matching',  # 매칭 조건/리스트/좋아요
    'chat',  # 대화방/메시지

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 정적파일(CSS 등)을 nginx 없이 Django만으로 서빙
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # allauth 최신 버전에서 필수로 요구하는 미들웨어
]

# 우리가 만든 커스텀 User 모델을 쓰겠다고 Django에 알려주는 설정.
# 반드시 첫 migrate 실행 전에 설정해야 한다 (나중에 바꾸면 DB를 다시 만들어야 함).
AUTH_USER_MODEL = 'accounts.User'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# 카카오 로그인 성공 시 우리 User 모델 필드를 자동으로 채워주는 어댑터.
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.KakaoSocialAccountAdapter'
# 일반(이메일/비밀번호) 회원가입을 막는 어댑터 - "카카오로만 로그인 가능" 원칙을 실제로 강제한다.
ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'

# 로그인/회원가입에 이메일·아이디·비밀번호를 따로 요구하지 않는다.
# (카카오 로그인만 지원하는 서비스이므로 자체 회원가입 폼 자체가 없음)
ACCOUNT_LOGIN_METHODS = {'username'}
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True  # 카카오 버튼 누르면 확인 화면 없이 바로 인가 요청

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_PROVIDERS = {
    'kakao': {
        'APPS': [
            {
                'client_id': os.environ.get('KAKAO_CLIENT_ID', ''),      # REST API 키
                'secret': os.environ.get('KAKAO_CLIENT_SECRET', ''),     # Client Secret
                'key': '',
            }
        ],
    }
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# 로컬 개발은 그냥 SQLite. 배포 플랫폼(Railway 등)이 Postgres를 붙여주면 DATABASE_URL
# 환경변수가 자동으로 채워지는데, 그게 있으면 그걸 쓰고 없으면 SQLite로 그대로 돌아간다.
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # `collectstatic`이 여기로 파일들을 모아준다 (배포용)
STORAGES = {
    # "staticfiles"만 새로 지정하고 "default"(사진 업로드 등에 쓰는 일반 파일 저장소)를
    # 빠뜨리면, Django는 STORAGES를 건드린 순간 둘 다 명시적으로 적어야 하는 걸로 취급해서
    # 자동으로 채워주지 않는다 - 그래서 얼굴/전신사진 등 ImageField.url을 쓰는 곳마다 에러가 났다.
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# 얼굴/전신사진 등 사용자 업로드 파일 저장 위치.
# 주의: 대부분의 배포 플랫폼(Railway 등)은 디스크가 "임시"라, 재배포하면 여기 저장된
# 파일이 통째로 사라질 수 있다. 1차 테스트 배포는 이대로 가도 되지만, 실제 서비스로 굳히려면
# Cloudflare R2 같은 외부 스토리지로 옮겨야 한다 (예전에 얘기했던 그 이유 그대로).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
