# Generated by Django 6.1.1 on 2026-09-24 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_regions', models.CharField(blank=True, max_length=300)),
                ('preferred_religions', models.CharField(blank=True, max_length=200)),
                ('preferred_smoking', models.CharField(blank=True, max_length=100)),
                ('preferred_height_code', models.CharField(blank=True, choices=[('M_160_170', '160~170'), ('M_170_180_UNDER', '170~180 미만'), ('M_180_UP', '180 이상'), ('F_150_DOWN', '150 이하'), ('F_150_160', '150~160'), ('F_160_170_UNDER', '160~170 미만'), ('F_170_180', '170~180')], max_length=20)),
                ('favorite_artists', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
