# Generated by Django 6.1.1 on 2026-09-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingpreference',
            name='favorite_artists',
        ),
        migrations.AddField(
            model_name='matchingpreference',
            name='favorite_artist_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='matchingpreference',
            name='favorite_artist_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='matchingpreference',
            name='favorite_artist_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='matchingpreference',
            name='preferred_hobby_dislike',
            field=models.CharField(blank=True, choices=[('GAME', '게임'), ('GYM', '헬스'), ('SPORTS', '스포츠 직접하기'), ('CAFE', '분위기 좋은 카페가기'), ('NETFLIX', '넷플릭스보기'), ('BASEBALL', '야구보기'), ('SOCCER', '축구보기'), ('WEBTOON', '만화보기'), ('READING', '책읽기')], max_length=20),
        ),
        migrations.AddField(
            model_name='matchingpreference',
            name='preferred_hobby_first',
            field=models.CharField(blank=True, choices=[('GAME', '게임'), ('GYM', '헬스'), ('SPORTS', '스포츠 직접하기'), ('CAFE', '분위기 좋은 카페가기'), ('NETFLIX', '넷플릭스보기'), ('BASEBALL', '야구보기'), ('SOCCER', '축구보기'), ('WEBTOON', '만화보기'), ('READING', '책읽기')], max_length=20),
        ),
        migrations.AddField(
            model_name='matchingpreference',
            name='preferred_hobby_second',
            field=models.CharField(blank=True, choices=[('GAME', '게임'), ('GYM', '헬스'), ('SPORTS', '스포츠 직접하기'), ('CAFE', '분위기 좋은 카페가기'), ('NETFLIX', '넷플릭스보기'), ('BASEBALL', '야구보기'), ('SOCCER', '축구보기'), ('WEBTOON', '만화보기'), ('READING', '책읽기')], max_length=20),
        ),
    ]
