# Generated by Django 6.1.1 on 2026-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_matchingpreference_preferred_hobby_dislike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchingpreference',
            name='preferred_height_code',
        ),
        migrations.AddField(
            model_name='matchingpreference',
            name='preferred_height_codes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
